### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mrsevic** [SomeoneElseOSM/SomeoneElse-style#2]
Hi! In general should I be concerned about the message below whilst importing the *.osm.pbf file:

**Failed to execute lua function for basic tag processing**

Thanks for your work and support

**Comment by SomeoneElseOSM** [comment]
It depends on the context of the error.  When I import UK data I see an error similar to this a couple of times:

    execute lua function for basic tag processing: /home/ajtown/data/SomeoneElse-style/style.lua:16: attempt to perform arithmetic on field 'layer' (a string value)
    Processing: Node(14770k 73.5k/s) Way(1938k 4.57k/s) Relation(0 0.00/s)Failed to execute lua function for basic tag processing: /home/ajtown/data/SomeoneElse-style/style.lua:16: attempt to perform arithmetic on field 'layer' (a string value)

That just means that some processing that the script was trying to do with the "layer" tag failed.  That's not a problem because it's just failing to process garbage data.  If your case is the same, don't worry about it, but if it's different, it might be something more serious.  Maybe you could provide a bit more detail about what's happening?

**Comment by Mrsevic** [comment]
Well to be honest whilst I was importing Montenegro that error never occurred. Then I returned to the previously created snapshot  and started importing Italy. I do not have a few errors it occurs literary on every processing node. 

I was following this tutorial with the similar configuration:

http://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1604_tileserver_load#Create_and_set_up_a_database

**Comment by SomeoneElseOSM** [comment]
If it's the same computer system, then it's likely a problem with the data, and whatever message appears to the right of "Failed to execute lua function for basic tag processing" will hopefully explain.  If it's a different computer system then it could be something more fundamental - like lua not installed.  However without any more context it's difficult to comment further.

**Comment by Mrsevic** [comment]
I've just repeated the tutorial. Tiles are not rendering unfortunately. Thanks anyways for your help.
