### ISSUE TITLE
Show map scale

### ISSUE THREAD

**Issue by hungerburg** [SomeoneElseOSM/SomeoneElse-style#22]
Leaflet has https://leafletjs.com/reference.html#control-scale - I think this is a must-have for a map.

**Comment by SomeoneElseOSM** [comment]
Fixed in https://github.com/SomeoneElseOSM/SomeoneElse-map/commit/a0f184648ccd62063d64ff306eb9f7d4db8ea828 .  Shift-refresh the map to reload the scripts, then press "controls" to toggle all 3 controls on and off.

On mobile the scale control can get hidden behind the attribution if a layer with a long attribution is turned on, but meh.
