### ISSUE TITLE
Duplication of labels on ways

### ISSUE THREAD

**Issue by SK53** [SomeoneElseOSM/SomeoneElse-style#3]
I've noticed a few of these around Coton in the Elms, but this example of [part ](https://www.openstreetmap.org/way/35390706)of NCN 63 just S of Ibstock really highlights that something odd is going on:

![screenshot 72](https://user-images.githubusercontent.com/5452818/34530788-2273d03a-f0a8-11e7-9263-59b66bb50e8a.png)

**Comment by SomeoneElseOSM** [comment]
It's a genuine problem, and I think it's related to the server that you're pointing at.  If you look at https://map.atownsend.org.uk/maps/map/map.html#zoom=14&lat=52.67336&lon=-1.38669 you shouldn't see the issue, and if you look at your previous URL it should forward to the newer one (as of about mid-afternoon today).

I've never bothered fixing it (on the test server) because I knew it wasn't a problem elsewhere and I am at some point planning to update osm2pgsql on there when I've got a version that'll do relation member rewriting (which I'd planned to look at over Christmas, but didn't get around to).

Of course, if you do see this on https://map.atownsend.org.uk/maps/map/map.html (or anywhere else with up to date software) then it'll need revisiting.

**Comment by SomeoneElseOSM** [comment]
Interestingly, the database usage on the server with this problem (which has just GB only in it) is half as much again as the one with GB+Ireland.  I haven't vacuumed either recently.
