### ISSUE TITLE
Hairdressers rendering at toilets

### ISSUE THREAD

**Issue by Dr-Mx** [SomeoneElseOSM/SomeoneElse-style#4]
[shop=hairdresser] is rendering as toilet: https://map.atownsend.org.uk/hot/21/1051315/703556.png

[male] and [female] tags can be used for hairdressers too: https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhairdresser

**Comment by SomeoneElseOSM** [comment]
Oops!  Now fixed (or at least, the fix is checked in):

![703556](https://user-images.githubusercontent.com/5311740/41439286-1a5d426a-7022-11e8-9d3f-5603eff0e360.png)

The "live" site will stay wrong until the database is reloaded, which I normally do at some frequency between once a week and once a month, but I'll try and do it overnight at some point in the next week.

**Comment by SomeoneElseOSM** [comment]
The database has been reloaded, and https://map.atownsend.org.uk/maps/map/map.html#zoom=19&lat=50.840054&lon=0.47011 now looks OK too.
